DROP IF EXISTS Pruebas;
CREATE DATABASE Pruebas;
USE DATABASE Pruebas;

/*Login*/
DROP USER IF EXISTS "Pruebas"@"%";
CREATE USER "Pruebas"@"%" IDENTIFIED BY "59LaU)0AOek-ydyE[";

GRANT
INSERT,SELECT,UPDATE,DELETE,
CREATE ROUTINE,ALTER ROUTINE,EXECUTE 
ON Pruebas.* 
TO "Pruebas"@"%";

/*Creacion de las tablas*/
CREATE TABLE Usuario(U_Nombre VARCHAR(30) NOT NULL,
U_ID INTEGER(8) NOT NULL PRIMARY KEY,
U_Contraseña INTEGER(20) NOT NULL,
U_Sal VARCHAR(100) NOT NULL,
U_Hash VARCHAR(88) NOT NULL,
U_Categoria ENUM ('Administrador','Jugador') DEFAULT 'Jugador',
U_registro datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Inicia(
usuario_CI INTEGER(8) UNSIGNED NOT NULL,
sesion_ID INTEGER(10) NOT NULL UNIQUE PRIMARY KEY,
fecha_abierta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
fecha_cerrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Sesion(
S_ID int(10) NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
S_estado ENUM('Abierta','Cerrada') DEFAULT 'Abierta'
);

CREATE TABLE Perfil(Pe_Nombre REFERENCES Usuario(U_Nombre),
Pe_ID INTEGER(8) NOT NULL PRIMARY KEY,
Pe_Puntaje REFERENCES Partida(Pa_Puntaje)
);

CREATE TABLE Partida(Pa_ID INTEGER(10) NOT NULL PRIMARY KEY;
/*Pa_Puntaje INTEGER(5)*/
);